import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: '📖 项目介绍',
    },
    {
      type: 'category',
      label: '📚 题目库',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '题目库',
        description: '所有已完成的算法题目',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'problems',
        },
      ],
    },
    {
      type: 'category',
      label: '🎯 知识点',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '知识点',
        description: '按数据结构和算法分类的知识体系',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'topics',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 算法模式',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '算法模式',
        description: '通用的解题模式和思维框架',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'patterns',
        },
      ],
    },
    {
      type: 'category',
      label: '📋 代码模板',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '代码模板',
        description: '常用算法的标准实现',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'templates',
        },
      ],
    },
    {
      type: 'category',
      label: '📝 复习系统',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '复习系统',
        description: '错题本和周总结',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'review',
        },
      ],
    },
  ],
};

export default sidebars;
