import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '开始',
    },
    {
      type: 'category',
      label: '题目库',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'problems',
        },
      ],
    },
    {
      type: 'category',
      label: '知识点',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'topics',
        },
      ],
    },
    {
      type: 'category',
      label: '算法模式',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'patterns',
        },
      ],
    },
    {
      type: 'category',
      label: '代码模板',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'templates',
        },
      ],
    },
    {
      type: 'category',
      label: '复习系统',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'review',
        },
      ],
    },
  ],
};

export default sidebars;
